version: 2

models:
  - name: stg_products
    description: "Modelo de staging para produtos com limpeza de dados"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: name
        tests:
          - not_null
      - name: price
        tests:
          - not_null
      - name: barcode
        tests:
          - not_null

  - name: stg_customers
    description: "Modelo de staging para clientes com limpeza de dados"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: email
        tests:
          - not_null
      - name: gender
        tests:
          - accepted_values:
              values: ['M', 'F', 'Outro', 'Indefinido']
